Repository jenkinsci/robot-plugin, pull requests merged in 2022-05, with the labels that each got.

#49 Bump dependency versions
  pom.xml
Labels: dependencies

#46 Adapt icon path removal from core
  src/main/resources/hudson/plugins/robot/model/RobotResult/sidepanel.jelly
Labels: maintenance

#48 Add passed and skipped cases to REST API response
  src/main/java/hudson/plugins/robot/model/RobotResult.java
  src/main/java/hudson/plugins/robot/model/RobotSuiteResult.java
Labels: enhancement

#50 Update README
  README.txt
Labels: documentation
